# permissions for end users to edit travellers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lab8
    app.kubernetes.io/managed-by: kustomize
  name: traveller-editor-role
rules:
- apiGroups:
  - traveller.example.com
  resources:
  - travellers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traveller.example.com
  resources:
  - travellers/status
  verbs:
  - get
