apiVersion: traveller.example.com/v1
kind: Traveller
metadata:
  labels:
    app.kubernetes.io/name: lab8
    app.kubernetes.io/managed-by: kustomize
  name: traveller-sample
spec:
  # TODO(user): Add fields here
